@HostAddressRoot = https://localhost:7291

###

GET {{HostAddressRoot}}/api/destinations?searchFor=us
Accept: application/json  

###


GET {{HostAddressRoot}}/api/destinations
Accept: application/json  

###
GET {{HostAddressRoot}}/api/itineraries?searchfor=ex
accept: application/json

###
GET {{HostAddressRoot}}/api/itineraries/1/stops
accept: application/json